### your site title here

title: Ryan Michael Kay
description: Personal Portfolio

baseurl: "/"" #name of GitHub repository

highlighter: rouge
markdown: kramdown

# Social media links in footer
twitter: "https://twitter.com/wiseAss301"
linkedin: "https://www.linkedin.com/in/ryan-kay-808388114/"
github: "https://github.com/BracketCove"

highlighter: rouge
markdown: kramdown

# Tracker
analytics:

#optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /projects/:path/

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
